"""add_is_maintainer_to_users

Revision ID: a86aa63eb011
Revises: a1b2c3d4e5f6
Create Date: 2026-07-25 13:51:39.129764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a86aa63eb011'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('modules_author_id_fkey', 'modules', type_='foreignkey')
    op.create_foreign_key(None, 'modules', 'users', ['author_id'], ['id'])
    op.add_column('users', sa.Column('is_maintainer', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_maintainer')
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.create_foreign_key('modules_author_id_fkey', 'modules', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
